import { BingoCell } from './types';

// 12 preset exhibitions + 4 custom slots
export const initialExhibitions: BingoCell[] = [
  {
    id: '1',
    type: 'preset',
    museum: '국립중앙박물관',
    exhibition: '인상주의에서 초기 모더니즘까지',
    isVisited: false,
    order: 0,
  },
  {
    id: '2',
    type: 'preset',
    museum: '국립현대미술관',
    exhibition: '김창열 회고전',
    isVisited: false,
    order: 1,
  },
  {
    id: '3',
    type: 'preset',
    museum: '예술의전당',
    exhibition: '빈센트 반 고흐',
    isVisited: false,
    order: 2,
  },
  {
    id: '4',
    type: 'preset',
    museum: '호암 미술관',
    exhibition: '겸재 정선',
    isVisited: false,
    order: 3,
  },
  {
    id: '5',
    type: 'preset',
    museum: '예술의전당',
    exhibition: '마르크 샤갈',
    isVisited: false,
    order: 4,
  },
  {
    id: '6',
    type: 'preset',
    museum: '아모레퍼시픽',
    exhibition: '마크 브래드 포드',
    isVisited: false,
    order: 5,
  },
  {
    id: '7',
    type: 'preset',
    museum: '한가람미술관',
    exhibition: '오랑주리 오르세',
    isVisited: false,
    order: 6,
  },
  {
    id: '8',
    type: 'preset',
    museum: '리움',
    exhibition: '이불',
    isVisited: false,
    order: 7,
  },
  {
    id: '9',
    type: 'preset',
    museum: '뮤지엄 산',
    exhibition: '안토니 곰리',
    isVisited: false,
    order: 8,
  },
  {
    id: '10',
    type: 'preset',
    museum: '코엑스',
    exhibition: '프리즈 Frieze',
    isVisited: false,
    order: 9,
  },
  {
    id: '11',
    type: 'preset',
    museum: '국립현대미술관',
    exhibition: '론 뮤익',
    isVisited: false,
    order: 10,
  },
  {
    id: '12',
    type: 'preset',
    museum: '국립중앙박물관',
    exhibition: '비엔나 1900',
    isVisited: false,
    order: 11,
  },
  // 4 custom slots
  {
    id: '13',
    type: 'custom',
    museum: '',
    exhibition: '',
    isVisited: false,
    order: 12,
  },
  {
    id: '14',
    type: 'custom',
    museum: '',
    exhibition: '',
    isVisited: false,
    order: 13,
  },
  {
    id: '15',
    type: 'custom',
    museum: '',
    exhibition: '',
    isVisited: false,
    order: 14,
  },
  {
    id: '16',
    type: 'custom',
    museum: '',
    exhibition: '',
    isVisited: false,
    order: 15,
  },
];
